project:
  type: website
  output-dir: docs

website:
  title: "Glasgow CompBio Community"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: nextEvent.qmd
        text: Next Event
      - href: previousEvents.qmd
        text: Previous Events

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    page-layout: full

editor: visual

