---
title: "Performance Comparison of Statistical Emulators for Parameter Estimation in Complex Systems"
description: "Submitted Talk"
draft: false
---

## Talk Details

**Time:** Tuesday, 14:45-15:05\
**Speaker:** Hongjin Ren\
**Topic:** Cardiology/Computational Methods\
**Type:** Submitted Talk

## Abstract

Mathematical models allow us to simulate complex systems, whose behaviour depends significantly on their underlying parameters. However, direct parameter inference of these systems typically involves repeatedly computing numerical solutions. Consequently, reducing the computational burden associated with parameter estimation is crucial for enhancing the practicality of these models. Statistical emulators present a promising solution to this issue, as they approximate mathematical models and substantially reduce computational demands.

Despite the potential benefits of emulators, selecting an appropriate emulation strategy remains challenging, primarily due to issues such as high dimensionality, sparse data and correlated outputs. In this study, we assess the effectiveness of various emulation strategies for parameter inference under different data scenarios. Our evaluation encompasses statistical models based on standard Gaussian Processes, variational Gaussian Processes, deep kernel learning, deep Gaussian Processes, and deep neural networks.

We construct several simulated data sets and analyse the parameter estimation accuracy of these models under different conditions, including output independence, different input-output dimensionality ratios and data sparsity. Our results demonstrate that the multi-output Gaussian Process consistently achieves superior parameter estimation accuracy compared to other Gaussian Process variants and deep neural networks, particularly in high-dimensional complex systems with multiple dependent outputs, and maintains greater stability in scenarios with sparse data.

These findings give insight into emulation strategies applicable to parameter estimation of high-dimensional complex systems and provide a foundation for the future development of real-time parameter estimation in practical applications.

------------------------------------------------------------------------

[← Back to Schedule](../schedule.html)
